config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'tweets#index'
  resources :tweets

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  mount_uploader :photo_url, PhotoUploader
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  # 유저가 login되있는지 안되있는지 체크부터 함(로그인 안되있으면 액션 허용 못하도록)
  before_action :authenticate_user!, except: [:index, :show]

  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Tweet.order(id: :desc).page(params[:page]) #kaminari사용해서 page nation
                    #    :id => :desc (desc 옮션까지 넣겠다.)
  end

  def new
    @tweet = Tweet.new

  end

  def create
    # @tweet = Tweet.new(
    #   title: params[:tweet][:title],
    #   content: params[:tweet][:content]
    # )
    # @tweet.save
    Tweet.create(tweet_params()) # strong parameter


    redirect_to tweets_path
  end

  def show
  end

  def edit
  end

  def update
    @tweet.update(tweet_params())
    redirect_to tweet_path(@tweet)

  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path
  end

  private
  def set_tweet()
    @tweet = Tweet.find(params[:id])
  end

  private
  def tweet_params()
     params.require(:tweet).permit(:title, :content, :user_id, :photo_url)
  #   params[:tweet][:title]
  #   params[:tweet][:content]   # white listing 내가 받을것만 명시하는것
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FormFor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to '트위터홈', root_path %>

<% if user_signed_in? %>
  <%= link_to '로그아웃', destroy_user_session_path, method: :delete %><br>
  <%= current_user.email %>님 환영합니다!<br>
<% else %>
  <%= link_to '로그인', new_user_session_path %>
<% end %>

<%= link_to '글쓰기', new_tweet_path %>


<p class="notice"><%= flash[:notice] %></p>
<p class="alert"><%= flash[:alert] %></p>


<%= yield %>

</body>
</html>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<h1>트윗 수정하기</h1>
<p></p>

<%= form_for(@tweet) do |t| %>
  제목: <%= t.text_field :title %><br>
  내용: <%= t.text_field :content %><br>
  <%= t.submit "수정하기" %>
<% end %>

app/views/tweets/index.html.erb
<h1>TWEETS LIST</h1>
<p></p>

<% @tweets.each do |t| %>
  제목 : <%= t.title %><br>
  내용 : <%= t.content%><br>
  글쓴이 : <%= t.user.email if t.user %><br>
  사진 : <%= image_tag t.photo_url %><br>
<%= link_to '트윗보기', "/tweets/#{t.id}" %><hr>
<% end %>

<%= paginate @tweets %>

app/views/tweets/new.html.erb
<h1>트윗하기</h1>
<p></p>

<%= form_for(@tweet) do |f| %>
  제목: <%= f.text_field :title %><br>
  내용: <%= f.text_field :content %><br>
  사진업로드: <%= f.file_field :photo_url %><br>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "트윗하기" %>
<% end %>

app/views/tweets/show.html.erb
<h1>TWEET 보기</h1>
<p></p>
제목: <%= @tweet.title %><br>
내용: <%= @tweet.content %><br>
<%= link_to "[수정]", edit_tweet_path(@tweet.id) %>
<%= link_to "[삭제]", tweet_path(@tweet.id), method: "delete"%>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>